### ISSUE TITLE
Document master trigger of documentation rebuild

### ISSUE THREAD

**Issue by iranzo** [Pelican-Elegant/documentation#32]
Document the setup that builds documentation website when master has new commit in 'elegant'

**Comment by iranzo** [comment]
@talha131 @silverhook @AWegnerGitHub ,
Can you please review https://iranzo.github.io/blog/2018/12/11/travis-to-trigger-build-in-another-repo/ as source for the PR that will close this issue?

Thanks
Pablo

**Comment by iranzo** [comment]
Context: It explain what was done on 'master' to trigger new build of website

**Comment by AWegnerGitHub** [comment]
Why did you manually build the table of contents instead of using `[TOC]`? Due to how close this issue and the one I created were on creation time, I'm guessing you didn't see https://github.com/Pelican-Elegant/documentation/issues/31

I'll give the content itself another read in a few hours. I read over it one though and nothing jumped out as confusing at that time.

**Comment by iranzo** [comment]
Hi,
I do use a editor extension that handles it in the same way in all markdown files I do use, I can replace them by '[TOC]' on the file I submit to the documentation website so that we do insist on the doogfooding.

Also this will probably need to tweak the pelicanconf.py file to use the MARKDOWN instead of MD_EXTENSION

If the content is OK, I can PR both [TOC] in prior and this document at the same time.

Thanks!
Pablo

**Comment by iranzo** [comment]
Fixed in #33 (TOC) and add new article
